INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('05','ANTIOQUIA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('08','ATLÁNTICO');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('11','BOGOTÁ, D.C.');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('13','BOLÍVAR');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('15','BOYACÁ');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('17','CALDAS');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('18','CAQUETÁ');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('19','CAUCA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('20','CESAR');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('23','CÓRDOBA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('25','CUNDINAMARCA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('27','CHOCÓ');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('41','HUILA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('44','LA GUAJIRA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('47','MAGDALENA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('50','META');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('52','NARIÑO');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('54','NORTE DE SANTANDER');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('63','QUINDÍO');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('66','RISARALDA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('68','SANTANDER');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('70','SUCRE');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('73','TOLIMA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('76','VALLE DEL CAUCA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('81','ARAUCA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('85','CASANARE');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('86','PUTUMAYO');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('88','SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('91','AMAZONAS');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('94','GUAINÍA');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('95','GUAVIARE');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('97','VAUPÉS');
INSERT INTO departamentos(dane_departamento, nombre_departamento) values ('99','VICHADA');
